// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Address struct {
	Address     string
	TrxBalance  string
	UsdtBalance string
	Status      string
	Error       string
	Attempts    int64
	CheckedAt   sql.NullTime
	CreatedAt   time.Time
}
