// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countByStatus = `-- name: CountByStatus :one
SELECT COUNT(*) FROM addresses WHERE status = ?
`

func (q *Queries) CountByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPending = `-- name: CountPending :one
SELECT COUNT(*) FROM addresses WHERE status = 'pending'
`

func (q *Queries) CountPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fetchPendingBatch = `-- name: FetchPendingBatch :many
SELECT address FROM addresses WHERE status = 'pending' LIMIT ?
`

func (q *Queries) FetchPendingBatch(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, fetchPendingBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAddress = `-- name: InsertAddress :execrows
INSERT INTO addresses (address) VALUES (?)
ON CONFLICT(address) DO NOTHING
`

func (q *Queries) InsertAddress(ctx context.Context, address string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAddress, address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAll = `-- name: ListAll :many
SELECT address, trx_balance, usdt_balance, is_activated, status, checked_at
FROM addresses
ORDER BY CAST(trx_balance AS REAL) DESC, address ASC
`

type ListAllRow struct {
	Address     string
	TrxBalance  string
	UsdtBalance string
	IsActivated bool
	Status      string
	CheckedAt   sql.NullTime
}

func (q *Queries) ListAll(ctx context.Context) ([]ListAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRow{}
	for rows.Next() {
		var i ListAllRow
		if err := rows.Scan(
			&i.Address,
			&i.TrxBalance,
			&i.UsdtBalance,
			&i.IsActivated,
			&i.Status,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChecked = `-- name: MarkChecked :exec
UPDATE addresses
SET trx_balance = ?,
    usdt_balance = ?,
    is_activated = ?,
    status = 'ok',
    attempts = attempts + 1,
    checked_at = CURRENT_TIMESTAMP,
    error = ''
WHERE address = ?
`

type MarkCheckedParams struct {
	TrxBalance  string
	UsdtBalance string
	IsActivated bool
	Address     string
}

func (q *Queries) MarkChecked(ctx context.Context, arg MarkCheckedParams) error {
	_, err := q.db.ExecContext(ctx, markChecked,
		arg.TrxBalance,
		arg.UsdtBalance,
		arg.IsActivated,
		arg.Address,
	)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE addresses
SET status = 'failed',
    attempts = attempts + 1,
    checked_at = CURRENT_TIMESTAMP,
    error = ?
WHERE address = ?
`

type MarkFailedParams struct {
	Error   string
	Address string
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, markFailed, arg.Error, arg.Address)
	return err
}

const resetAll = `-- name: ResetAll :exec
UPDATE addresses
SET status = 'pending',
    attempts = 0,
    error = '',
    is_activated = 0,
    checked_at = NULL
`

func (q *Queries) ResetAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAll)
	return err
}
